logLevel: info
rtsp: yes
rtspAddress: :8554
api: yes
apiAddress: 127.0.0.1:9997
metrics: yes
metricsAddress: 127.0.0.1:9998

paths:
  all_others:
    source: publisher
    sourceOnDemand: no
    record: yes
    recordPath: /recordings/%path/%Y-%m-%d_%H-%M-%S-%f
    recordFormat: fmp4
    recordPartDuration: 1s
    recordSegmentDuration: 2s
    recordDeleteAfter: 2m
